# Generated by Django 5.1.5 on 2026-02-03 22:38

import dirtyfields.dirtyfields
import django.db.models.deletion
import django.utils.timezone
import machtms.backend.DocumentManager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=12)),
                ('country', models.TextField(default='US')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contractor', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Carrier',
                'verbose_name_plural': 'Carriers',
            },
        ),
        migrations.CreateModel(
            name='DocumentContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FactoringContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('company_name', models.TextField()),
                ('phone', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('street_address', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('invoice_id', models.IntegerField(default=30100)),
                ('logo_src', models.URLField(blank=True)),
                ('invoice_remit_message', models.CharField(blank=True, max_length=200)),
                ('payroll_cutoff', models.IntegerField(choices=[('SUNDAY', [(0, 'SUN')]), ('MONDAY', [(1, 'MON')]), ('TUESDAY', [(2, 'TUE')]), ('WEDNESDAY', [(3, 'WED')]), ('THURSDAY', [(4, 'THU')]), ('FRIDAY', [(5, 'FRI')]), ('SATURDAY', [(6, 'SAT')])], default=4)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='machtms.address')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='DocumentQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_hash_id', models.TextField()),
                ('is_complete', models.BooleanField(default=False)),
                ('document_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_queues', to='machtms.documentcontext')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.TextField(blank=True, default='')),
                ('bol_number', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('times_missing', 'Times Missing'), ('rescheduled', 'Rescheduled'), ('claim', 'Claim'), ('at_hub', 'At Hub'), ('complete', 'Complete'), ('tonu', 'TONU')], default='pending', max_length=20)),
                ('billing_status', models.CharField(choices=[('paperwork_pending', 'Paperwork Pending'), ('pending_delivery', 'Pending Delivery'), ('billed', 'Billed'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending_delivery', max_length=20)),
                ('trailer_type', models.CharField(blank=True, choices=[('SMALL_20', "20'"), ('SMALL_28', "28'"), ('MEDIUM_40', "40'"), ('MEDIUM_45', "45'"), ('LARGE_48', "48'"), ('LARGE_53', "53'")], default='', max_length=20)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='machtms.customer')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
            ],
            options={
                'verbose_name': 'Load',
                'verbose_name_plural': 'Loads',
            },
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.ForeignKey(help_text='The load this leg belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='machtms.load')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
            ],
            options={
                'verbose_name': 'Leg',
                'verbose_name_plural': 'Legs',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='GoogleCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('expiry', models.DateTimeField()),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
            ],
            options={
                'abstract': False,
                'unique_together': {('email', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='GmailInvoiceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processing', 'PROCESSING'), ('success', 'SUCCESS'), ('error', 'ERROR')], default='processing', max_length=20)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machtms.load')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GmailBillingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_credentials', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='machtms.googlecredentials')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_config', to='machtms.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FactoringDefaultSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='machtms.factoringcontact')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='factoringcontact',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization'),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='machtms.address')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='machtms.carrier')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='DocumentResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted', models.TextField()),
                ('status_message', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('matched_loads', models.JSONField()),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machtms.documentqueue')),
                ('load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.load')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='documentcontext',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization'),
        ),
        migrations.CreateModel(
            name='DirectUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_hash_id', models.TextField()),
                ('object_key', models.TextField()),
                ('filename', models.TextField()),
                ('content_type', models.TextField()),
                ('category', models.CharField(choices=[('RC', 'Customer Rate Confirmation'), ('CRC', 'Carrier Rate Confirmation'), ('INVOICE', 'Invoice'), ('POD', 'Proof of Delivery'), ('LUMPER', 'Lumper'), ('RECEIPT', 'Receipts'), ('OTHER', 'Other')], max_length=50)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='machtms.load')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machtms.customer')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
            ],
            options={
                'verbose_name': 'Customer Representative',
                'verbose_name_plural': 'Customer Representatives',
            },
        ),
        migrations.CreateModel(
            name='CustomerAP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('payment_type', models.CharField(choices=[('quickpay', 'Quick Pay'), ('standard', 'Standard Pay')], default='standard', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machtms.customer')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
            ],
            options={
                'verbose_name': 'Customer AP',
                'verbose_name_plural': 'Customer APs',
            },
        ),
        migrations.AddField(
            model_name='carrier',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization'),
        ),
        migrations.CreateModel(
            name='AddressUsageByCustomerAccumulate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_usages_accumulate', to='machtms.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_usages_accumulate', to='machtms.customer')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
            ],
            options={
                'verbose_name': 'Address Usage (by Customer)',
                'verbose_name_plural': 'Address Usages (by Customer)',
            },
        ),
        migrations.CreateModel(
            name='AddressUsageAccumulate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machtms.address')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='address',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization'),
        ),
        migrations.CreateModel(
            name='AccountsPayableContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_emails', to='machtms.customer')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountRep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(blank=True)),
                ('phone', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machtms.customer')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationAPIKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50)),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='machtms.organization')),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostShipmentDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_key', models.TextField()),
                ('filename', models.TextField()),
                ('category', models.CharField(choices=[('RC', 'Customer Rate Confirmation'), ('CRC', 'Carrier Rate Confirmation'), ('INVOICE', 'Invoice'), ('POD', 'Proof of Delivery'), ('LUMPER', 'Lumper'), ('RECEIPT', 'Receipts'), ('OTHER', 'Other')], max_length=50)),
                ('content_type', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True)),
                ('load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='machtms.load')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='S3UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_key', models.CharField(max_length=200)),
                ('filename', models.TextField()),
                ('category', models.CharField(choices=[('RC', 'Customer Rate Confirmation'), ('CRC', 'Carrier Rate Confirmation'), ('INVOICE', 'Invoice'), ('POD', 'Proof of Delivery'), ('LUMPER', 'Lumper'), ('RECEIPT', 'Receipts'), ('OTHER', 'Other')], max_length=50)),
                ('content_type', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s3_uploads', to='machtms.documentqueue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionUploadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration', models.DateTimeField(default=machtms.backend.DocumentManager.models.get_expiration_time)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machtms.load')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShipmentAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.ForeignKey(help_text='The carrier assigned to this leg', on_delete=django.db.models.deletion.CASCADE, related_name='shipment_assignments', to='machtms.carrier')),
                ('driver', models.ForeignKey(help_text='The driver assigned to this leg', on_delete=django.db.models.deletion.CASCADE, related_name='shipment_assignments', to='machtms.driver')),
                ('leg', models.ForeignKey(help_text='The leg this assignment is for', on_delete=django.db.models.deletion.CASCADE, related_name='shipment_assignments', to='machtms.leg')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
            ],
            options={
                'verbose_name': 'Shipment Assignment',
                'verbose_name_plural': 'Shipment Assignments',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'IDLE'), ('processing', 'PROCESSING'), ('success', 'COMPLETE'), ('error', 'ERROR')], default='idle', max_length=20)),
                ('message', models.TextField(blank=True, default='idling')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration', models.DateTimeField(default=machtms.backend.DocumentManager.models.get_expiration_time)),
                ('direct_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload_log', to='machtms.directupload')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_logs', to='machtms.sessionuploadlog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_list_index', models.IntegerField(default=0)),
                ('activePath', models.CharField(blank=True, default='/api/loads/same_day', max_length=1056)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfile',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_number', models.PositiveIntegerField(help_text='Order of this stop within the leg')),
                ('start_range', models.DateTimeField(help_text='The earliest time the stop can occur')),
                ('end_range', models.DateTimeField(help_text='The latest time the stop can occur (optional)', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When this stop was created')),
                ('action', models.CharField(choices=[('LL', 'LIVE LOAD'), ('LU', 'LIVE UNLOAD'), ('HL', 'HOOK LOADED'), ('LD', 'DROP LOADED'), ('EMPP', 'EMPTY PICKUP'), ('EMPD', 'EMPTY DROP'), ('HUBP', 'HUB PICKUP'), ('HUBD', 'HUB DROPOFF')], help_text='The type of action to be performed at this stop', max_length=4)),
                ('po_numbers', models.TextField(blank=True, default='', help_text='Purchase order numbers associated with this stop')),
                ('driver_notes', models.TextField(blank=True, default='', help_text='Notes for the driver regarding this stop')),
                ('address', models.ForeignKey(help_text='The address where this stop takes place', on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='machtms.address')),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='machtms.leg')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
            ],
            options={
                'verbose_name': 'Stop',
                'verbose_name_plural': 'Stops',
                'ordering': ['stop_number'],
                'unique_together': {('stop_number', 'leg')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
