# Generated by Django 5.1.5 on 2026-02-22 17:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machtms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentassignment',
            name='leg',
            field=models.OneToOneField(help_text='The leg this assignment is for', on_delete=django.db.models.deletion.CASCADE, related_name='shipment_assignment', to='machtms.leg'),
        ),
        migrations.CreateModel(
            name='ParsingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('completed', 'Completed'), ('partially_failed', 'Partially Failed'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
            ],
        ),
        migrations.CreateModel(
            name='RateConDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('pending', 'Pending'), ('processing', 'Processing'), ('parsed', 'Parsed'), ('misclassified', 'Misclassified'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('original_filename', models.TextField()),
                ('s3_key', models.TextField()),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='machtms.parsingsession')),
            ],
        ),
        migrations.CreateModel(
            name='ParsedRateCon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True)),
                ('structured_data', models.JSONField(blank=True, null=True)),
                ('classification_passed', models.BooleanField(default=True)),
                ('classification_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machtms.load')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_content', to='machtms.ratecondocument')),
            ],
        ),
    ]
