# Generated by Django 5.1.5 on 2026-02-25 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machtms', '0002_alter_shipmentassignment_leg_parsingsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='place_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='carrier',
            name='mc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='carrier',
            name='usdot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='parsedratecon',
            name='load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.load'),
        ),
        migrations.CreateModel(
            name='CarrierAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zip_code', models.TextField()),
                ('country', models.TextField()),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='carrier',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.carrieraddress'),
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zip_code', models.TextField()),
                ('country', models.TextField()),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='machtms.customeraddress'),
        ),
    ]
