# Generated by Django 5.1.5 on 2026-02-27 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machtms', '0003_address_place_name_carrier_mc_carrier_usdot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratecondocument',
            name='classification_passed',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='ratecondocument',
            name='classification_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ratecondocument',
            name='load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machtms.load'),
        ),
        migrations.AlterField(
            model_name='address',
            name='place_name',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='ParsedRateCon',
        ),
    ]
