# Generated by Django 5.1.5 on 2026-03-01 02:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machtms', '0004_remove_parsedratecon_add_fields_to_ratecondocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresignedURLEntryPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presigned_url', models.TextField()),
                ('s3_key', models.TextField()),
                ('filename', models.TextField()),
                ('expiration', models.DateTimeField()),
                ('status', models.CharField(choices=[('orphaned', 'Orphaned'), ('processed', 'Processed')], default='orphaned', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machtms.organization')),
            ],
        ),
    ]
